language: node_js
node_js: 
    - 'node'

cache: npm

script: npm run build:prod

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: gh-pages
  
#after_script:
  #- git checkout gh-pages
  #- git add -f dist
  #- git commit -m 'deploy'
  #- git subtree push --prefix dist origin gh-pages

#branches:
 # only:
 # - master

notifications:
  email: true