language: node_js
node_js: 
    - 'node'

cache:
  directories:
  - node_modules

script: 
  - npm run build:prod

deploy:
  - git checkout gh-pages
  - git add -f dist
  - git commit -m 'deploy'
  - git subtree push --prefix dist origin gh-pages

branches:
  only:
  - master    

notifications:
  email: true
