language: node_js
node_js: 
    - 'node'

cache: npm

script: npm run build:prod

deploy:
provider: pages
skip_cleanup: true
github_token: '8bdbf779fc75e368921c4393881b89f67385faab'
local_dir: dist
on:
  branch: master

notifications:
  email: true
