language: node_js
node_js: 
    - 'node'

branches:
  only:
  - master    

cache:
  directories:
  - node_modules

script: npm run build:prod

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
target-branch: gh-pages
verbose: true
on:
  branch: master

notifications:
  email: true
