language: node_js
node_js: '14.7.0' #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm i

script:
  - npm run build:prod

# script: npm run build:prod
deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
on:
  branch: gh-pages

after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git checkout -b gh-pages
  - git add -f dist
  - git commit -m 'deploy'
  - git subtree push --prefix dist origin gh-pages

# 只有指定的分支提交时才会运行脚本
branches:
 only:
 - master

notifications:
  email: true
